### PR TITLE
Active Directory Plugin

### PR DESCRIPTION
**Pull request by eshanks16**
Active Directory often has an impact on the performance of your vSphere environment. This plugin contains 8 scripts used to check on Active Directory health as well as security issues and stale records.

### CODE REVIEW

**Comment by Sneddo** [comment]
Thanks the for the contribution. I think I'd prefer to split these plugins out to a separate vCheck-AD project, personally. Especially since most of these plugins are not specific to vSphere implementations. e.g. returning all locked out users, not just service accounts used by vCenter, etc.

Perhaps a good time to migrate vCheck vSphere to the [vCheckReport](https://github.com/vCheckReport) organization and create new repos for vCheck-AD, Exchange, DFS, etc.

**Comment by eshanks16** [comment]
It's up to you. Obviously you're in charge of the repository so do what you think is best. I'm happy to place the plugin wherever you'd like it. I originally had a AD only vCheck based on the existing code that Alan published, but thought that the community might want it. I'm available if you make a decision on it.
Thanks.

**Comment by Sneddo** [comment]
Yeah, I'll leave this open and see what @alanrenouf thinks. 

I think I'll create a vCheck-AD repo in the vCheckReport org anyway, since it's something I think a lot of people could use.

**Comment by Sneddo** [comment]
I've created a new repository under the vCheckReports organization for [vCheck-AD](https://github.com/vCheckReport/vCheck-AD). Some of your code got added, with some minor modifications in some cases.

Thanks for your input!

**Pull request closed without merging**
