### PR TITLE
This solve some Problems running vCheck on Docker and Linux enviroment :)

### PR DESCRIPTION
**Pull request by ascii42**
- fix to work on powershell 6
- fix some linux compatibilities
- works with the powerclicore docker image

### CODE REVIEW

**Comment by lucdekens** [comment]
Thanks for this extensive contribution, really impressive.

Just some questions before I try to merge this.
- is there some kind of README that summarises your changes?
- the plugin renames are a breaking change. What is your main justification for that?

On the practical side, the PR is quite extensive.
In fact, I will need to do any conflict resolution and merge from the command line (change is too complex according to GitHub).
Could you consider breaking this 1 PR up into a number of PR?
Perhaps a PR per set of changes that logically belong together?

**Comment by lucdekens** [comment]
@ascii42 please have a look at the comments on your PR

**Comment by ascii42** [comment]
> Thanks for this extensive contribution, really impressive.
> 
> Just some questions before I try to merge this.
> 
> * is there some kind of README that summarises your changes?
> * the plugin renames are a breaking change. What is your main justification for that?
> 
> On the practical side, the PR is quite extensive.
> In fact, I will need to do any conflict resolution and merge from the command line (change is too complex according to GitHub).
> Could you consider breaking this 1 PR up into a number of PR?
> Perhaps a PR per set of changes that logically belong together?

Well, the rename of the Plugin directory doesn't matter and break any functions, i've changed it on my working copy 'cause handling files on my linux workstation was easier for me on the command line, i.e. tab completion escape characters etc...
maybe there are one or two interesting new plugins in the plugin directory.

the most important files are vCheck.ps1, files Style/*/Style.ps1 files, GlobalVariables.ps1 and the Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1

this small changes should resolve the problems with working on linux or docker env and make it portable from windows to linux.

**Comment by lucdekens** [comment]
Thanks for your reply, but I'm afraid that "_... the rename of the Plugin directory doesn't matter and break any functions,_" is not true.
Users that schedule vCheck and use the **Job** parameter have an XML file that lists all the plugins to use.
With the file renames those XML files will be broken.

On being able to run in a Linux environment, how did you solve the credential file(s) issue?
The functions Get-vCenterCredentials and Set-vCenterCredentials seem to have disappeared from your code.
Several users on Windows platforms are making use of the credential files.

**Comment by ascii42** [comment]
> Thanks for your reply, but I'm afraid that "_... the rename of the Plugin directory doesn't matter and break any functions,_" is not true.
> Users that schedule vCheck and use the **Job** parameter have an XML file that lists all the plugins to use.
> With the file renames those XML files will be broken.
> 
> On being able to run in a Linux environment, how did you solve the credential file(s) issue?
> The functions Get-vCenterCredentials and Set-vCenterCredentials seem to have disappeared from your code.
> Several users on Windows platforms are making use of the credential files.

argh, ok two things that i've not thought about yet -.-
i, totally agree with you, ok a new installation should work, old will break.
well, the credential store is a problem, i guess it doesn't work on pscore yet, maybe it can be fixed with an if or try-catch, depends on the psversion if desktop, try to catch stored creds or on a plain setup ask the user if he wants to store in file or cred store....

urgh, hmm maybe i should starting use windows again.

well, i can place a new commit with renamed plugin dir, but it does not fix the cred problem

**Comment by lucdekens** [comment]
All is not lost.
You/we could update the code so that it takes two paths, depending on the platform it is running on.

The DPAPI based credentials PowerShell is using on Windows platforms will indeed not work on non-Windows platforms.
Perhaps the code use a built-in encryption on the Linux platform in that case.
Worst case, a clear text file.

On a practical note, what can we use from your PR that doesn't involve file renames and does not use 
 credentials?
I did notice you introduced some new plugins, those we could use I guess?

I haven't looked in detail at all 100+ files in this PR.
Perhaps you have a better view of the changes in the PR that can be used without impact?
Perhaps in a new PR?

**Comment by ascii42** [comment]
> All is not lost.
> You/we could update the code so that it takes two paths, depending on the platform it is running on.
> 
> The DPAPI based credentials PowerShell is using on Windows platforms will indeed not work on non-Windows platforms.
> Perhaps the code use a built-in encryption on the Linux platform in that case.
> Worst case, a clear text file.
> 
> On a practical note, what can we use from your PR that doesn't involve file renames and does not use
> credentials?
> I did notice you introduced some new plugins, those we could use I guess?
> 
> I haven't looked in detail at all 100+ files in this PR.
> Perhaps you have a better view of the changes in the PR that can be used without impact?
> Perhaps in a new PR?

ok sorry for wasting your time, my intention was to create a version that works in my case on photon in a docker container to get rid of the windows machine that was used before and so my focus was to solve my problem.

some password hashing sounds good :)

so what can we use hmm... plugins will be an extra pr it will be easier so you should have a look in vCheck.ps1 there are some \/ problems that will be solved, case sensitive and hostname was also a problem in my case in the Style/*/Style.ps1 there will be also an if for that problem.
i guess, in vCheck.ps1 will be a also a fix for psversion and maybe thereis something in also in the connection plugin that breaks before, i'm not sure right now (maybe lang/ uname fixies)

**Comment by alanrenouf** [comment]
Closing for now but want to revisit this once we have the new version up and running

**Pull request closed without merging**
