### PR TITLE
HardeningGuide

### PR DESCRIPTION
**Pull request by techgecko**
HardeningGuide plugins, settings fixed.

### CODE REVIEW

**Comment by alanrenouf** [comment]
Did you run through an initial config after you had added these as I get errors on the initial config for each one.

**Comment by alanrenouf** [comment]
A few comments....
 1. Awesome work, looks like some great new enhancements
 2. We already have a plugin that checks NTP servers, do you think we should remove your duplicate plugin?
 3. I suggest you do the New-VIProperties in the 00 Connection plugin as this will mean you dont have to reuse the Get-VM cmdlet and cause a lot of extra calls (and time) in larger environments
4. Remember the idea behind this script is to show people the issues that exist and may cause an issue over the next day or week, not an audit report. Some of the results returned are more of an audit which is fine but may be better in a security hardening report with just these plugins and not this specific vCheck report, I would be interested in your thoughts here.

**Comment by techgecko** [comment]
1. Thanks! I've learned so much looking through your code and all the contributors and am glad to finally share something back.
2. I agree there's another NTP plugin, but mine is integrated into the Hardening Guide scripts and accepts the -Remediate command to FIX it when it finds a server that's different. Keep reading 3i below and WHY will make more sense.
3. I may misunderstand, but the "New-VIProperty" command is only in VM-disable-autoinstall-Harden.ps1 and used once per vCenter, so would run the same number of times (1) with the same impact in either location. I tried to avoid changes to your framework files since the command is only needed if someone chooses to use the HardeningGuide plugins.
3i. I realize now I didn't explain HOW to use this... I made a complete copy of the vCheck subfolders dedicated to the the HardeningGuide audit/remediation and REMOVE all others. It would not make sense (and make a VERY cluttered report) to mix these plugins with the other health ones. I run the hardening guide script & plugins only against our two PCI vCenter environments, and from a separate set of folders/scripts run the "regular" vCheck with select plugins against ALL our vCenters (including PCI) to check general health. We follow our change control process before running the HardeningGuide script with the -Remediate argument.

**Comment by alanrenouf** [comment]
Following this I would recommend we create a new report purely for the hardening guide as at the moment we dont have the option to use the core framework and easily choose what set of plugins you want to use, I want to get to the point where all of the projects are under this one and the first time it starts up it says Which report do you want to use: vSphere, vCloud, Hardening Guide, etc ....

**Comment by Sneddo** [comment]
Yeah, agreed. I love the idea here, it's just not the right fit for this repo. It's the reason this pull request is not merged and not closed, because I'm not really sure the best way to integrate it in without having to maintain multiple repos of the same code (submodules don't really seem to fit this use-case). 

Ideally I'd like to see vCheck (core functionality) as a separate project to the plugins I think. The report selection could potentially tie into an update mechanism which checks online and downloads from the appropriate repository.

**Comment by vScripter** [comment]
I'm adding a 3rd consensus to get this added as a separate vCheck Report, all together; hosted on the [vCheck-Report](https://github.com/vCheckReport) Repo (any three of us can help you get that going)

With that being said, I'm going to close this PR out.

**Pull request closed without merging**
