### PR TITLE
Create vcheckHelpers.ps1

### PR DESCRIPTION
**Pull request by omrsafetyo**
My VMware architect was looking for help parsing data from the vCheck HTML output files.  I built this helper function that will take the vCheck HTML output file, and the plugin/section as inputs, and convert all of the entries for that item into a Powershell object.

Example: 
Get-vCheckLogData -vCheckFile vcenter01_vCheck_2016080823.htm -Section "VMs Powered Off"

I am running v6.23 of vCheck, but this appears to work correctly for the input files that I have available to test with, for any section/plugin I have tested.

### CODE REVIEW

**Comment by Sneddo** [comment]
To be honest, if this is a feature that people would find useful, it would make more sense to add a line into the report generation to export a CSV or something easier to work with, rather than messing with HTML. That way any changes to the style won't break this as well.

**Comment by omrsafetyo** [comment]
Yeah that would probably make more sense.  But I thought this might be useful for people (like myself) who have a year+ of old HTML logs that might want to parse through them.  This function (as is) could be used to create the CSV files - for instance, if you were to upgrade to a version of vCheck that supports export to CSV, this could be used to migrate the HTML files to CSV.

**Comment by Sneddo** [comment]
Yeah true. Just realised we could add this to the existing vCheckUtils.ps1 anyway, to save us from having another file in the project.

**Comment by Sneddo** [comment]
Manually added to vCheckUtils.ps1 and committed

**Pull request closed without merging**
