### PR TITLE
Remove duplicated plugin "107 Quantity of Snapshots"

### PR DESCRIPTION
**Pull request by haripetrov**
Plugin "107 Quantity of Snapshots" is duplicated with "106 Find Phantom
Snapshots", "85 Snapshot Activity", "79 Find VMs in Uncontrolled
Snapshot Mode", "64 Snapshots Oversize", "45 VMs needing snapshot
consolidation" and "02 Snapshot Information".

### CODE REVIEW

**Comment by haripetrov** [comment]
P.S. 
[Off topic] The milestone for 6.21 is completed so you can close it.

**Comment by Sneddo** [comment]
hmmmm I'm not sure..., I guess it is a bit more lightweight than the other plugins, so some people might find it beneficial if they just want a quick overview of snapshots. I definitely think we could consolidate some of these though...

Fixed up the milestone though, thanks for that.

**Comment by haripetrov** [comment]
This information can be found in "64 Snapshots Oversize" (tab "SnapCount") so I don't see the point in having several plugins for the same thing.
My idea about the milestone 6.21 concerns the fact that it is already completed and can be closed (the whole milestone I mean because we already have 6.22). :)

**Comment by Sneddo** [comment]
Yeah OK, I see your point.

I think in the longer term we should look at consolidating some of these into "Snapshot Information" and "Snapshot Problems" type plugins...

**Comment by haripetrov** [comment]
I agree with you. 6 plugins for Snapshots are too much.

**Pull request merged**
