### PR TITLE
Bug fix #400

### PR DESCRIPTION
**Pull request by omrsafetyo**
This should really only contain a bug fix for the issue reported in issue #400.  

The fix for this was correcting the PARAM block in the Get-HttpDataStoreItem function of 00 Initialize/00 Connection Plugin for vCenter.ps1.  There were some non-ascii characters in place of quotes in the PARAM block.

However, it looks like my default editor has also modified several other files for spacing.  This fork was freshly merged (pushed) from the master branch before making edits.  Most of these changes are just spacing, the only actual changes are noted above (4 quotation marks).  It looks like it also, for instance, updated a couple windows carriage returns (^M) to newlines in the same function.  Reviewing the changes should show there are no issues, and this should fix the issue reported in #400

### CODE REVIEW

**Comment by omrsafetyo** [comment]
Added additional functionality to satisfy #204  

The changes are very basic and should be non-breaking.  I have moved the $Server variable from the 00 Connection Plugin to the GlobalVariables and renamed to $Servers.  In vCheck.ps1 I have wrapped the processing logic in a for loop, after splitting the $Servers variable on comma.  This will allow you to define multiple vCenters into a single string, and processing will work.

Currently this sends 1 report per vCenter which I think is the expected default behavior, since $Server is used in the default title

**Comment by Sneddo** [comment]
Please submit all PRs to the dev branch

**Comment by Sneddo** [comment]
On second look, I don't think we'll merge this into the main dev branch but perhaps as a feature branch instead. The changes modify the vCheck core too much, which will make porting updates the the other vCheck projects more effort.

Finishing the work on the settings handling may be a better option- at least then the per-vCenter settings are contained in one config file and we could support multiple configs for vCheck. Now just to find the time to do it.

**Comment by omrsafetyo** [comment]
Yeah I noticed the config settings change after submitting, when I was reviewing open issues.

My first pull request is a bug fix.  The only change is fixing some characters that it looks like came in from an editor having markup characters in it. There are some spacing changes as well, I think that is the reason why the delta is so large - but when it comes right down to it, I have swapped 4 non-ascii characters for quotation marks.  That is up to https://github.com/alanrenouf/vCheck-vSphere/pull/605/commits/22219944e5074aa355952dd8cc32feb19ee2f812 

The second change, https://github.com/alanrenouf/vCheck-vSphere/pull/605/commits/6dfe6d0935b967e83de574f33ad89c0e10254e59 is the feature change.  If you'd like to reject that pull request, and direct me to the branch you want it in, I can send a new pull request.

**Comment by Sneddo** [comment]
Yeah, I'll need to have a look at it at some point. A lot of those are probably already fixed in the dev branch.

**Comment by omrsafetyo** [comment]
Ah yes, you're right both the carriage returns and mark-up quotations are fixed in dev.  I apologize, I'm still new to contributing to projects, and GitHub in general.  I'll switch the to the dev branch and see how that goes.

**Comment by Sneddo** [comment]
No worries, I still struggle with it when it's not a simple click to merge! Thanks for the contribution.

**Pull request closed without merging**
