### PR TITLE
Update 98 vSwitch Security.ps1

### PR DESCRIPTION
**Pull request by danbarr**
A number of logical and formatting fixes to this plugin:
1. Ignore ForgedTransmits on vDS Uplink port groups.
2. Expanded ForEach-Object aliases and ran thru VS Code's formatter.
3. Fixed several logic bugs which prevented some checks from returning expected results.
4. Removed unused $vSwitchSecurityCheck setting and redundant plugin variable block.
5. Fixed the settings logic so a vSwitch or port group only appears if one of the conditions you've selected to report on is true.

### CODE REVIEW

**Comment by danbarr** [comment]
Also this may resolve Issue #550, would need @jmachado81 to confirm.

**Comment by Sneddo** [comment]
Nice work. I might clean it up a bit at some point, but worth merging the fixes first I think.

**Comment by jmachado81** [comment]
Is there a way to have this output the vSS hostname to remedy the security
issues?

**Comment by danbarr** [comment]
Definitely agree it could still use some cleanup. Just wanted to get it returning the expected results first. I put it through some paces in my lab and think it should at least be doing that now.

**Pull request merged**
