### PR TITLE
Merge master to dev

### PR DESCRIPTION
**Pull request by alanrenouf**
Moving direct master changes back to dev so its up to date

### CODE REVIEW

**Comment by alanrenouf** [comment]
Can someone check this for me please, @Sneddo @vScripter ?

**Comment by vScripter** [comment]
@alanrenouf Sure thing; I’ll check this morning.

**Comment by alanrenouf** [comment]
Actually I think this may be overwriting some of the changes made to dev that were newer than master so I need a better way to do this.

**Comment by Sneddo** [comment]
Ah bugger, didn't notice that PR was to master -_-

Could be a little tedious to sort this out...a lot of it can be merged without any trouble as it is new files, but we may need to work through some of them and check.

**Comment by alanrenouf** [comment]
Let me know how and I can do it, just not sure of best way

**Comment by Sneddo** [comment]
I think we can probably just merge. The big diffs seem to be just a text encoding or something. I did a pull to master just before the hackathon, so worst case we shouldn't lose too many updates...and just review any commits to the core code.

**Pull request merged**
